# -*- coding: utf-8 -*-
"""CPCE Asg 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CQ3cRnS9qZ5lvuP9kiwOGc10TyzqXvnu
"""

#Q.1
# To Determine the bearing capacity of soil with a water table
BulkDensity = float(input("Enter the value of Bulk Density of soil:"))
SatDensity = float(input("Enter the value of Saturated Density of soil:"))
WaterDensity = float(input("Enter the unit Weight of Water:"))
Df = float(input("Enter the value of depth of footing:"))
Dw = float(input("Enter the value of water table above footing level:"))
Dw1 = float(input("Enter the value of Water table below the level of footing:"))
B = float(input("Enter the value of width of footing:"))
Nq = float(input("Enter the value of Nq:"))
Ng = float(input("Enter the value of Ng:"))

# Submerged Weight of soil
SubDensity = BulkDensity - WaterDensity
print("Submerged Weight of soil is:", SubDensity)

# CASE A
print("CASE A")
qu = (SubDensity * Df * Ng) + (0.5 * 0.8 * B * SubDensity * Nq)
print("The value of ultimate bearing capacity of soil is:", qu)

# Approximate calculation of Bearing capacity of soil
Rw = 0.5 + 0.5 * (Dw / B)
print("The value of Rw is:", Rw)
Rw1 = 0.5 + 0.5 * (Dw1 / 8)
print("The value of Rw1 is:", Rw1)
qu = (BulkDensity * Df * Ng * Rw) + (0.5 * 0.8 * 8 * BulkDensity * Nq * Rw1)
print("The approximate value of ultimate bearing capacity of soil is:", qu)

# CASE B
print("CASE B")
qu = (BulkDensity * Df * Nq) + (0.5 * 0.8 * 8 * SubDensity)
print("The value of ultimate bearing capacity is:", qu)

# CASE C
print("CASE C")
x = float(input("Enter the value of depth of water below footing:"))
qu = (BulkDensity * Ng) + (0.5 * 0.8 * (BulkDensity * x + SubDensity * (B - x))) * Nq
print("The value of ultimate bearing capacity is:", qu)

#Q.2
UCS = float(input("Enter the value of UCS of soil:"))
Cu = UCS / 2
B = float(input("Enter the value of dimension of pile:"))
l = float(input("Enter the length of pile:"))
Alpha = float(input("Enter the value of adhesion factor:"))
Nc = float(input("The value of Nc: "))
Ab = B * B
print("The Base area of footing is:", Ab)
As = 4 * B * l  # Assuming 4 sides of the pile
print("The value of cohesion of soil is:", Cu)
Qpu = Cu * Nc * Ab
print("Qpu:", Qpu)
Qf = Alpha * Cu * As
print("Qf:", Qf)
Qu = Qpu + Qf
print("The value of load-carrying capacity of the pile is (Qu):", Qu)

#Q.3
BulkDensity = float(input("Enter the value of Bulk Density of soil:"))
SatDensity = float(input("Enter the value of Saturated Density of soil:"))
WaterDensity = float(input("Enter the unit Weight of Water:"))
Df = float(input("Enter the value of depth of footing:"))
B = float(input("Enter the value of width of footing:"))
Ng = float(input("Enter the value of Ng:"))
N_Gamma = float(input("Enter the value of N gamma (N):"))
SubDensity = SatDensity - WaterDensity
print("Submerged Weight of soil is:", SubDensity)

M = int(input("Number of data values of Water table above footing level: "))
N = int(input("Number of data values of Water table below footing level: "))
Dw = []
Dw1 = []

for i in range(1, M + 1):
    print("Enter the value of water table above footing level measured w.r.t. ground (Dw): ")
    Depth_Dw = float(input())
    Dw.append(Depth_Dw)
    Rw = 0.5 + 0.5 * (Depth_Dw / B)
    print("The value of Rw is:", Rw)

for j in range(1, N + 1):
    print("Enter the value of water table below footing level measured w.r.t. ground (Dw1): ")
    Depth_Dw1 = float(input())
    Dw1.append(Depth_Dw1)
    Rw1 = 0.5 + 0.5 * (Depth_Dw1 / B)
    print("The value of Rw1 is:", Rw1)

qu = (BulkDensity * Df * Ng * Rw) + (0.5 * 0.8 * B * BulkDensity * N_Gamma * Rw1)
print("qu:", qu, "kN/m^2")