# -*- coding: utf-8 -*-
"""CPCE Asg 11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZCeTXMQoehFc_bzBW4_qZ_JU8ZU5iWh3
"""

class ConstructionTask:
    def __init__(self, task_name, total_hours):
        self.task_name = task_name
        self.total_hours = total_hours
        self.hours_completed = 0
        self.is_completed = False

    def complete_task(self, hours_worked):
        if not self.is_completed:
            self.hours_completed += hours_worked
            if self.hours_completed >= self.total_hours:
                self.is_completed = True
                self.hours_completed = self.total_hours

    def __str__(self):
        status = "Completed" if self.is_completed else "Incomplete"
        return f"Task: {self.task_name} ({status}) - {self.hours_completed}/{self.total_hours} hours"

def main():
    tasks = []

    while True:
        print("\nConstruction Progress Tracker")
        print("1. Add Task")
        print("2. Update Task")
        print("3. List All Tasks")
        print("4. End Task")

        choice = input("Enter your choice: ")

        if choice == "1":
            task_name = input("Enter task name: ")
            total_hours = int(input("Enter total hours required: "))
            new_task = ConstructionTask(task_name, total_hours)
            tasks.append(new_task)
            print(f"Task '{task_name}' added.")

        elif choice == "2":
            if not tasks:
                print("No tasks to update.")
            else:
                print("Tasks:")
                for i, task in enumerate(tasks):
                    print(f"{i + 1}. {task.task_name}")
                task_index = int(input("Select task to update (1 to {}): ".format(len(tasks))))
                if 1 <= task_index <= len(tasks):
                    hours_worked = int(input("Enter hours worked on the task: "))
                    tasks[task_index - 1].complete_task(hours_worked)
                    print("Task updated.")

        elif choice == "3":
            if not tasks:
                print("No tasks added yet.")
            else:
                for task in tasks:
                    print(task)

        elif choice == "4":
            print("Ending Progress Tracker.")
            break

        else:
            print("Invalid choice. Please select a valid option.")

if __name__ == "__main__":
    main()